main: felipe221.skywars.Main
name: SkyWars
version: '1.0'
description: Plugin privado - Felipe221
author: Felipe221
api-version: 1.16
commands:
  sw:
    description: SW Private
    permission: skywars.config
  leave:
    description: Salir de una arena
    aliases: /exit
